el1 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().resourceId(\"com.supportgenie.argenie:id/mic_iv\").instance(1)")
el1.click()
el2 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.ImageView\").instance(8)")
el2.click()
el4 = driver.find_element(by=AppiumBy.ID, value="com.supportgenie.argenie:id/message_textview")
el4.send_keys("test")
el5 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="TODO")
el5.click()
el6 = driver.find_element(by=AppiumBy.ID, value="com.supportgenie.argenie:id/chat_back_btn_iv")
el6.click()
el7 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().resourceId(\"com.supportgenie.argenie:id/video_lly\").instance(1)")
el7.click()
el8 = driver.find_element(by=AppiumBy.ID, value="com.supportgenie.argenie:id/faq_btn")
el8.click()
el9 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().text(\"How do I get a surface detected?\")")
el9.click()
el10 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().resourceId(\"com.supportgenie.argenie:id/arrow_icon\").instance(0)")
el10.click()
el11 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().text(\"What is the recommended distance of the device from the surface to be detected?\")")
el11.click()
el12 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().resourceId(\"com.supportgenie.argenie:id/arrow_icon\").instance(1)")
el12.click()
el13 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().text(\"What document types are supported in the chat section of the app?\")")
el13.click()
el14 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().text(\"Under what lighting conditions does the app function properly?\")")
el14.click()
el15 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().resourceId(\"com.supportgenie.argenie:id/ly_ques\").instance(4)")
el15.click()
el16 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().text(\"Does the app work on rough surfaces?\")")
el16.click()
el17 = driver.find_element(by=AppiumBy.ID, value="com.supportgenie.argenie:id/logo")
el17.click()
driver.execute_script('mobile: pressKey', {"keycode": 4})
el18 = driver.find_element(by=AppiumBy.ID, value="com.supportgenie.argenie:id/create_rec_btn")
el18.click()
el19 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Menu_open")
el19.click()
el20 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Menu close")
el20.click()
el21 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Arrow")
el21.click()
el22 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Circle")
el22.click()
el23 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Draw")
el23.click()
el24 = driver.find_element(by=AppiumBy.ID, value="com.supportgenie.argenie:id/ar_text_iv")
el24.click()
el25 = driver.find_element(by=AppiumBy.CLASS_NAME, value="android.widget.EditText")
el25.send_keys("test")
el26 = driver.find_element(by=AppiumBy.ID, value="android:id/button1")
el26.click()
el27 = driver.find_element(by=AppiumBy.ID, value="com.supportgenie.argenie:id/ar_options_iv")
el27.click()
el28 = driver.find_element(by=AppiumBy.ID, value="com.supportgenie.argenie:id/ar_arrow_left_iv")
el28.click()
el29 = driver.find_element(by=AppiumBy.ID, value="com.supportgenie.argenie:id/ar_arrow_right_iv")
el29.click()
el30 = driver.find_element(by=AppiumBy.ID, value="com.supportgenie.argenie:id/ar_arrow_up_iv")
el30.click()
el31 = driver.find_element(by=AppiumBy.ID, value="com.supportgenie.argenie:id/ar_arrow_down_iv")
el31.click()
el32 = driver.find_element(by=AppiumBy.ID, value="com.supportgenie.argenie:id/ar_anchor_setting_close")
el32.click()
el33 = driver.find_element(by=AppiumBy.ID, value="com.supportgenie.argenie:id/remove_anchors")
el33.click()
el34 = driver.find_element(by=AppiumBy.ID, value="android:id/button1")
el34.click()
el35 = driver.find_element(by=AppiumBy.ID, value="com.supportgenie.argenie:id/demoEndBtn")
el35.click()
